### PR TITLE
Update fork-this.md

### PR DESCRIPTION
**Pull request by troutcolor**
Changed a verse probably for the worse.

For what it is worth, I was a bit confused by this as I first forked the original repo then edited my own. So pull request went to my own. I deleted that repo and forked by clicking the pencil. (I should have read Alans excellent instructions a bit better).

### CODE REVIEW

**Comment by cogdog** [comment]
Great opening verse. I also saw in reviewing the pull request I think I could edit it too. I should have tried....

**Comment by troutcolor** [comment]
I now see my fork is:
This branch is 2 commits behind cogdog:gh-pages.

I wonder how I would get it up to date. on the desktop I would, I think, git rebase would do it but I am not sure how to do that with forked repo? I'll click about;-)

**Comment by troutcolor** [comment]
looks like you need a local thing to catch up with a project you have forked from:
http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository

but
http://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381

That seemed to do the trick, but was confusing.

**Comment by cogdog** [comment]
I think this is helpful, but a lot to unpack. This is what worries me about
sending people here! Will play with it, thanks

On Wed, Apr 6, 2016 at 9:47 AM, troutcolor notifications@github.com wrote:

> looks like you need a local thing to catch up with a project you have
> forked from:
> 
> http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository
> 
> but
> 
> http://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381
> 
> That seemed to do the trick, but was confusing.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/cogdog/fork-on-the-range/pull/3#issuecomment-206459874

## 

*------------------------------------------------------------------------------------Alan
Levine: A Cog, A Dog, A Blog *
cog.dog • yep, that's my domain!

blog: cogdogblog.com  • tweets: @cogdog http://twitter.com/cogdog

photos: flickr http://flickr.com/photos/cogdog & Barking Dog Studios
http://barkingdog.me • code: github.com/cogdog
50+ Web Ways to Tell a Story http://50ways.wikispaces.com • pechaflickr
http://pechaflickr.net • ds106 http://ds106.us/
_------------------------------------------------------------------------------------_

**Pull request merged**
